# Site settings
title: <div class="InSession">
header-img: img/home-bg.png
email: connor.gallopo@me.com
copyright_name: connorgallopo
description: > # this means to ignore newlines until "baseurl:"
  My path through an education that's right for me.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: connorgallopo
github_username:  connorgallopo
learn_profile: connorgallopo
email_username: connor.gallopo@me.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
